version: 2.1
executors:
  node_executor:
    docker:
      - image: circleci/node:14-buster
        auth:
          username: $DOCKER_USER_RO
          password: $DOCKER_PASSWORD_RO

jobs:

  # DEBUG: fake version update
  extractOpenAPISpec:
    executor: node_executor
    steps:
      - prepare
      - attach_workspace:
          at: ~/project
      - run:
          name: Extract OpenAPI JSON
          command: |
            mkdir -p .openapidoc/spec
            cp .specsource/teku.json .openapidoc/spec/teku.json
      - run:
          name: DEBUG generate api spec
          working_directory: .openapidoc
          command: |
            node debug-generate.js
      - store_artifacts:
          path: .openapidoc/spec/teku.json
      - persist_to_workspace:
          root: ~/project
          paths:
            - .openapidoc/spec/teku.json

  publishOpenApiSpec:
    executor: node_executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "54:c2:42:9c:85:ee:a0:ba:7c:83:85:2f:79:b0:0a:7c"
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - node-cache-{{ checksum "./.openapidoc/package-lock.json" }}
            - node-cache-
      - run:
          name: install
          working_directory: .openapidoc
          command: |
            npm ci
      - run:
          name: Build Folder
          working_directory: .openapidoc
          command: |
            OA_GIT_USERNAME=$CIRCLE_USERNAME OA_GIT_EMAIL="${CIRCLE_USERNAME}@users.noreply.github.com" OA_GIT_URL=$CIRCLE_REPOSITORY_URL OA_GH_PAGES_BRANCH="gh-pages" node publish.js
      - save_cache:
          paths:
            - ~/.npm
          key: node-cache-{{ checksum "./.openapidoc/package-lock.json" }}

workflows:
  circleci:
    jobs:
      - extractOpenAPISpec
      - publishOpenApiSpec:
          filters:
            branches:
              only:
                - master
                - /^release-.*/
            tags: # stable doc is published only on tags to prevent confusion on the doc site.
              only: /.*/
          requires:
            - extractAPISpec
          context:
            - dockerhub-quorumengineering-ro
